on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install aqua
        # Based on aqua-installer's workflow:
        # https://github.com/aquaproj/aqua-installer/blob/6d5ae97847bbfae6727f7e98543a026dd5b4bf5e/action.yaml
        run: |
          set -ex

          curl -sSfL -O https://raw.githubusercontent.com/aquaproj/aqua-installer/v4.0.5/aqua-installer
          echo '451028d56959cc738564885b1dbebc2691ea038ffde04e2472e4d486a3591146  aqua-installer' | sha256sum -c -
          chmod +x aqua-installer
          ./aqua-installer
          rm aqua-installer

          echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin" >> $GITHUB_PATH

      - name: Install deps
        run: cd updater && aqua i

      - name: Configure git
        run: |
          set -ex
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Check for updates
        id: updater
        run: cd updater && ./update.nu --commit

      - if: steps.updater.outputs.changed
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: Updates for Chromium ${{ steps.updater.outputs.chromium-version }}
          body: '*Automatically generated by the `updater` workflow.*'
          branch: auto-update-${{ steps.updater.outputs.chromium-version }}-${{ steps.updater.outputs.short-tree }}
